### ISSUE TITLE
ksonnet workspace has no kube config

### ISSUE THREAD

**Issue by jaxx0r** [rbo/RedHatHackathon-KubeFlow-Demo#4]
when in terminal of ksonnet-worker:

Authentication required for https://master.berlin-5194.openshiftworkshop.com:443 (openshift)
Username: ****
Password: ****
Login successful.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    kube-public
    kube-service-catalog
    kube-system
  * kubeflow
 .....

Using project "kubeflow".
error: KUBECONFIG is set to a file that cannot be created or modified: /.kube/config; caused by: mkdir /.kube: permission denied
sh-4.2$ ks init kubeflow
ERROR No current context found. Make sure a kubeconfig file is present

**Comment by rbo** [comment]
fixed
